config/routes.rb
FantasyCongressLeague::Application.routes.draw do
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :login, only: [] do
    resources :password, only: [:new, :create, :show, :edit, :update], path_names: {edit: 'recover'}
  end
  resources :users, only: [:new, :create, :show]
  resource  :user, only: [:edit, :update], controller: :users
  resources :settings, only: [:edit, :update]
  resources :leagues do
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :team_members, only: [:new, :create] do
        member do
          put :activate, action: :update, defaults: {rpc: 'activate'}
          put :leader, action: :update, defaults: {rpc: 'leader'}
          put :whip, action: :update, defaults: {rpc: 'whip'}
          post :recruit, action: :update, defaults: {rpc: 'recruit'}
          delete :vacate, action: :destroy, defaults: {rpc: 'vacate'}
          delete :recess, action: :destroy, defaults: {rpc: 'recess'}
          delete :retire, action: :destroy, defaults: {rpc: 'retire'}
        end
      end
      resources :tradings, only: [:create, :destroy]
      resources :activity, only: [:index, :show], controller: :annals
      resources :scoresheets, only: [:index]
    end
    member do
      post :authenticate
    end
  end
  get '/leagues/open/page/:id', to: 'leagues#index', as: 'leagues_open', defaults: {state: 'open'}
  get '/leagues/playing/page/:id', to: 'leagues#index', as: 'leagues_playing', defaults: {state: 'playing'}

  resources :legislators, only: [:show, :index] do
    resources :activity, only: [:index, :show], controller: :annals
  end
  get '/legislators/status/:status/page/:id', to: 'legislators#index', as: 'legislators_status'
  get '/legislators/party/:party/page/:id', to: 'legislators#index', as: 'legislators_party'
  get '/legislators/chamber/:chamber/page/:id', to: 'legislators#index', as: 'legislators_chamber'
  get '/legislators/gender/:gender/page/:id', to: 'legislators#index', as: 'legislators_gender'
  get '/legislators/name/:alpha/page/:id', to: 'legislators#index', as: 'legislators_name'
  get '/legislators/page/:id', to: 'legislators#index', as: 'legislators_page'
  get '/legislators/page/:id/:limit', to: 'bills#index', as: 'legislators_page_limit'

  resources :committees, only: [:index, :show]
  get '/committees/page/:id', to: 'committees#index', as: 'committees_page'
  get '/committees/page/:id/:limit', to: 'bills#index', as: 'committees_page_limit'

  resources :bills, only: [:index, :show]
  get '/bills/page/:id', to: 'bills#index', as: 'bills_page'
  get '/bills/page/:id/:limit', to: 'bills#index', as: 'bills_page_limit'
  get '/bills/chamber/:chamber/page/:id', to: 'bills#index', as: 'bills_chamber'
  get '/bills/status/:status/page/:id', to: 'bills#index', as: 'bills_status'
  get '/bills/docket/page/:id', to: 'bills#index', as: 'bills_docket', defaults: {docket: true}

  resource :capital_hill, only: [:show], controller: :capital_hill

  get  'help' => 'home#help'
  get  'statistics' => 'home#statistics'
  root to: 'home#show'
end

app/controllers/capital_hill_controller.rb
class CapitalHillController < ApplicationController
  before_filter :require_current_user

  def show
  	@teams = current_user.teams.legal.includes(:league)
    @leagues = League.where commissioner_id: current_user_id
  end
end

app/views/capital_hill/show.html.erb
<div class="page-header">
  <h2>Capital Hill</h2>
  <p>Next ranking update in <%= distance_of_time_in_words Time.now, UpdateRankingsJob.scheduled_to_run_at %></p>
</div>

<ul class="nav nav-tabs">
  <li class='active'><a href="#teams" data-toggle="tab">Your Teams</a></li>
  <li><a href="#leagues" data-toggle="tab">Your Leagues</a></li>
  <li>
    <%= link_to new_league_path do %>
      <span class="glyphicon glyphicon-plus"></span>
      New League
    <% end %>
  </li>
</ul>
<br />

<div class='tab-content'>
  <div id='teams' class='tab-pane active'>
    <p>Here you see an overview your active teams, their league standing, and actions you must take like drafting.</p>
    <table class='table table-bordered table-striped'>
      <% if @teams.empty? %>
        <tr>
          <td colspan="4">
            <br/>
            <p>You have not formed any teams yet. To form a new team, <%= link_to 'join', leagues_path %> or <%= link_to 'start', new_league_path %> a league.</p>
            <br/>
          </td>
        </tr>
      <% else %>
        <tr><th>Team</th><th>League</th><th>Standing</th><th>Status</th></tr>
      <% end %>
      <% @teams.each do |team| %>
        <tr>
          <td><%= link_to team.name, edit_league_team_path(team.league, team) %></td>
          <td><%= link_to team.league.name ,league_path(team.league) %></td>
          <td><%= team.standing_rank %> : <%= pluralize number_with_delimiter(team.points), 'point' %></td>
          <td>
            <% if team.league.drafting? && !team.league.can_play? && team == team.league.current_drafting_team %>
              <strong><%= link_to 'Your turn to draft!', new_league_team_team_member_path(team.league, team) %></strong>
            <% elsif team.league.drafting? && team.league.can_play? %>
              Waiting to start
            <% elsif team.league.drafting? %>
              Drafting, round <%= team.league.draft_round+1 %>
            <% else %>
              <%= team.league.status %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div id='leagues' class='tab-pane'>
    <p>Here you see an overview your the leagues you are commissioning, and any actions you must take as commissioner like starting to draft or play.</p>
    <table class='table table-bordered table-striped'>
      <% if @leagues.empty? %>
        <tr>
          <td colspan="4">
            <br/>
            <p>You are not currently commsioner for any active leagues. <%= link_to 'Start a league', new_league_path %>.</p>
            <br/>
          </td>
        </tr>
      <% else %>
        <tr><th>Name</th><th>Teams</th><th>Format</th><th>Status</th></tr>
      <% end %>
      <% @leagues.each do |league| %>
        <tr>
          <td><%= link_to league.name, edit_league_path(league) %></td>
          <td><%= "#{league.teams.size}/#{league.slots}" %></td>
          <td><%= league.tournament %></td>
          <td>
            <% if league.drafting? && league.can_play? %>
              Waiting to start
            <% elsif league.drafting? %>
              Drafting, round <%= league.draft_round+1 %>
            <% else %>
              <%= league.status %>
            <% end %>
            
          </td>
        </tr>
      <% end %>
    </table>    

  </div>
</div>