config/routes.rb
FantasyCongressLeague::Application.routes.draw do
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :login, only: [] do
    resources :password, only: [:new, :create, :show, :edit, :update], path_names: {edit: 'recover'}
  end
  resources :users, only: [:new, :create, :show]
  resource  :user, only: [:edit, :update], controller: :users
  resources :settings, only: [:edit, :update]
  resources :leagues do
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :team_members, only: [:new, :create] do
        member do
          put :activate, action: :update, defaults: {rpc: 'activate'}
          put :leader, action: :update, defaults: {rpc: 'leader'}
          put :whip, action: :update, defaults: {rpc: 'whip'}
          post :recruit, action: :update, defaults: {rpc: 'recruit'}
          delete :vacate, action: :destroy, defaults: {rpc: 'vacate'}
          delete :recess, action: :destroy, defaults: {rpc: 'recess'}
          delete :retire, action: :destroy, defaults: {rpc: 'retire'}
        end
      end
      resources :tradings, only: [:create, :destroy]
      resources :activity, only: [:index, :show], controller: :annals
      resources :scoresheets, only: [:index]
    end
    member do
      post :authenticate
    end
  end
  get '/leagues/open/page/:id', to: 'leagues#index', as: 'leagues_open', defaults: {state: 'open'}
  get '/leagues/playing/page/:id', to: 'leagues#index', as: 'leagues_playing', defaults: {state: 'playing'}

  resources :legislators, only: [:show, :index] do
    resources :activity, only: [:index, :show], controller: :annals
  end
  get '/legislators/status/:status/page/:id', to: 'legislators#index', as: 'legislators_status'
  get '/legislators/party/:party/page/:id', to: 'legislators#index', as: 'legislators_party'
  get '/legislators/chamber/:chamber/page/:id', to: 'legislators#index', as: 'legislators_chamber'
  get '/legislators/gender/:gender/page/:id', to: 'legislators#index', as: 'legislators_gender'
  get '/legislators/name/:alpha/page/:id', to: 'legislators#index', as: 'legislators_name'
  get '/legislators/page/:id', to: 'legislators#index', as: 'legislators_page'
  get '/legislators/page/:id/:limit', to: 'bills#index', as: 'legislators_page_limit'

  resources :committees, only: [:index, :show]
  get '/committees/page/:id', to: 'committees#index', as: 'committees_page'
  get '/committees/page/:id/:limit', to: 'bills#index', as: 'committees_page_limit'

  resources :bills, only: [:index, :show]
  get '/bills/page/:id', to: 'bills#index', as: 'bills_page'
  get '/bills/page/:id/:limit', to: 'bills#index', as: 'bills_page_limit'
  get '/bills/chamber/:chamber/page/:id', to: 'bills#index', as: 'bills_chamber'
  get '/bills/status/:status/page/:id', to: 'bills#index', as: 'bills_status'
  get '/bills/docket/page/:id', to: 'bills#index', as: 'bills_docket', defaults: {docket: true}

  resource :capital_hill, only: [:show], controller: :capital_hill

  get  'help' => 'home#help'
  get  'statistics' => 'home#statistics'
  root to: 'home#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end

  def help; end

  def statistics
    @bill_count = Bill.count
  end
end

app/views/home/help.html.erb
<div class='page-header'>
  <h2>Help</h2>
</div>

<h4>Scoring Points</h4>

<table>
  <tr><th>Activity</th><th>Score</th></tr>
  <tr><td>Sponsoring Legislation</td><td>20 points</td></tr>
  <tr><td>&bull; Passed House</td><td>+5 points</td></tr>
  <tr><td>&bull; Passed Senate</td><td>+5 points</td></tr>
  <tr><td>&bull; Signed by President</td><td>+10 points</td></tr>
  <tr><td>&bull; Override Veto</td><td>+50 points</td></tr>
  <tr><td>Co-Sponsoring Legislation</td><td>10 points</td></tr>
  <tr><td>&bull; Passed House</td><td>+1 points</td></tr>
  <tr><td>&bull; Passed Senate</td><td>+1 points</td></tr>
  <tr><td>&bull; Signed by President</td><td>+5 points</td></tr>
  <tr><td>&bull; Override Veto</td><td>+10 points</td></tr>
</table>

app/views/home/show.html.erb
<div class="jumbotron">
  <div class="container">
    <p>Fantasy Congress League is a free educational web game where you draft a team of senators and representatives to compete for legislative and civic accomplishment.</p>

    <ol class="list-inline">
      <li class="<%= logged_in? && 'active' %>">
        <%= link_to_if !logged_in?, '1. Register', new_user_path %>
      </li>
      <li class="active">2. Join a League</li>
      <li class="active">3. Draft a Team</li>
      <li class="active">4. Play</li>
    </ol>
    <p>
      <%= link_to 'Join league', leagues_path, class: "btn btn-primary btn-lg" %> or 
      <%= link_to 'Start league', new_league_path, class: "btn btn-primary btn-lg" %>
    </p>
  </div>
</div>

<p class="lead">
  Now playing the <strong>113th</strong> United States Congress. <strong><%= pluralize(days_remaining_in_congress, 'day') %></strong> remaining for league play.
</p>

<div class="row">
  <div class="col-md-3 col-sm-3 col-xs-6 center">
    <%= link_to legislators_path, class: 'plain' do %>
      <div class="thumbnail">
        Research
        <br />
        <img data-src="holder.js/300x200" alt="...">
        <div class="caption">
          <h2>Legislators</h2>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3 col-sm-3 col-xs-6 center">
    <%= link_to committees_path, class: 'plain' do %>
      <div class="thumbnail">
        Research
        <br />
        <img data-src="holder.js/300x200" alt="...">
        <div class="caption">
          <h2>Committees</h2>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3 col-sm-3 col-xs-6 center">
    <%= link_to bills_path, class: 'plain' do %>
      <div class="thumbnail">
          Research
          <br />
          <img data-src="holder.js/300x200" alt="...">
          <div class="caption">
            <h2>Bills</h2>
          </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3 col-sm-3 col-xs-6 center">
    <%= link_to statistics_path, class: 'plain' do %>
      <div class="thumbnail">
        Research
        <br />
        <img data-src="holder.js/300x200" alt="...">
        <div class="caption">
          <h2>Statistics</h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/statistics.html.erb
<div class='page-header'>
  <h2>Statistics : 113th Congress</h2>
</div>

<p>There are <%= number_with_delimiter @bill_count %> bills and resolutions currently before the United States Congress. Of those, only about 5% will become law. They must be enacted before the end of the 2013-2015 session (the “113th Congress”).</p>