config/routes.rb
FantasyCongressLeague::Application.routes.draw do
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :login, only: [] do
    resources :password, only: [:new, :create, :show, :edit, :update], path_names: {edit: 'recover'}
  end
  resources :users, only: [:new, :create, :show]
  resource  :user, only: [:edit, :update], controller: :users
  resources :settings, only: [:edit, :update]
  resources :leagues do
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :team_members, only: [:new, :create] do
        member do
          put :activate, action: :update, defaults: {rpc: 'activate'}
          put :leader, action: :update, defaults: {rpc: 'leader'}
          put :whip, action: :update, defaults: {rpc: 'whip'}
          post :recruit, action: :update, defaults: {rpc: 'recruit'}
          delete :vacate, action: :destroy, defaults: {rpc: 'vacate'}
          delete :recess, action: :destroy, defaults: {rpc: 'recess'}
          delete :retire, action: :destroy, defaults: {rpc: 'retire'}
        end
      end
      resources :tradings, only: [:create, :destroy]
      resources :activity, only: [:index, :show], controller: :annals
      resources :scoresheets, only: [:index]
    end
    member do
      post :authenticate
    end
  end
  get '/leagues/open/page/:id', to: 'leagues#index', as: 'leagues_open', defaults: {state: 'open'}
  get '/leagues/playing/page/:id', to: 'leagues#index', as: 'leagues_playing', defaults: {state: 'playing'}

  resources :legislators, only: [:show, :index] do
    resources :activity, only: [:index, :show], controller: :annals
  end
  get '/legislators/status/:status/page/:id', to: 'legislators#index', as: 'legislators_status'
  get '/legislators/party/:party/page/:id', to: 'legislators#index', as: 'legislators_party'
  get '/legislators/chamber/:chamber/page/:id', to: 'legislators#index', as: 'legislators_chamber'
  get '/legislators/gender/:gender/page/:id', to: 'legislators#index', as: 'legislators_gender'
  get '/legislators/name/:alpha/page/:id', to: 'legislators#index', as: 'legislators_name'
  get '/legislators/page/:id', to: 'legislators#index', as: 'legislators_page'
  get '/legislators/page/:id/:limit', to: 'bills#index', as: 'legislators_page_limit'

  resources :committees, only: [:index, :show]
  get '/committees/page/:id', to: 'committees#index', as: 'committees_page'
  get '/committees/page/:id/:limit', to: 'bills#index', as: 'committees_page_limit'

  resources :bills, only: [:index, :show]
  get '/bills/page/:id', to: 'bills#index', as: 'bills_page'
  get '/bills/page/:id/:limit', to: 'bills#index', as: 'bills_page_limit'
  get '/bills/chamber/:chamber/page/:id', to: 'bills#index', as: 'bills_chamber'
  get '/bills/status/:status/page/:id', to: 'bills#index', as: 'bills_status'
  get '/bills/docket/page/:id', to: 'bills#index', as: 'bills_docket', defaults: {docket: true}

  resource :capital_hill, only: [:show], controller: :capital_hill

  get  'help' => 'home#help'
  get  'statistics' => 'home#statistics'
  root to: 'home#show'
end

app/models/bill.rb
class Bill
  include Mongoid::Document
  include Mongoid::Timestamps::Updated

  field :name, type: String
  field :official_title, type: String
  field :category, type: String
  field :number, type: String
  field :status, type: String
  field :congress, type: Integer, default: 113
  field :subjects, type: Array
  field :introduced_at, type: Date
  field :summary, type: String
  field :related, type: Array

  embeds_one :sponsor, cascade_callbacks: true
  embeds_many :cosponsors, class_name: 'Sponsor', cascade_callbacks: true
  embeds_many :referrals, cascade_callbacks: true
  embeds_many :actions, as: :legislation, cascade_callbacks: true
  has_many :amendments
  index 'referrals._id' => 1

  after_create :annal

  scope :current, where(congress: 113)
  scope :house,   where(category: { '$in' => ['h','hr']})
  scope :senate,  where(category: { '$in' => ['s','sres']})
  scope :joint,   where(category: { '$in' => ['sconres','sjres','hconres','hjres']})
  scope :introduced, where(status: 'INTRODUCED')
  scope :referred, where(status: { '$in' => ['REFERRED','REPORTED']})
  scope :defeated, where(status: { '$in' => ['FAIL:ORIGINATING:HOUSE','FAIL:ORIGINATING:SENATE','PROV_KILL:SUSPENSIONFAILED','PROV_KILL:CLOTUREFAILED']})
  scope :enacted,  where(status: { '$in' => ['PASSED:CONCURRENTRES','ENACTED:SIGNED','PASSED:SIMPLERES','PASSED:BILL']})

  def short_title
    "#{category.upcase}-#{number}"
  end

  def display_name
    case category
    when 'hconres', 'sconres'
      'Concurrent Resolution ' << number
    when 'h'
      'House Bill ' << number
    when 's'
      'Senate Bill ' << number
    when 'sjres', 'hjres'
      'Joint Resolution ' << number
    when 'sres'
      'Senate Resolution ' << number
    when 'hr'
      'House Resolution ' << number
    else
      category.upcase
    end
  end

  def cosponsor_ids
    cosponsors.map(&:_id)
  end

  def status_description
    status
  end

  def related_bills
    @related_bills ||= if related.blank?
      Array.new
    else
      Bill.where(id: {'$in' => related})
    end
  end

  def last_action
    actions.last
  end

  private

    def annal
      if sponsor
        a = Annal.where(parent_id: self._id, parent_type: 'Bill', legislator_id: sponsor._id, category: 'sponsored_legislation').first_or_initialize
        a.created_at = introduced_at
        a.save

        Scoresheet.count! sponsor.id, :sponsored_bills, introduced_at
      end

      unless cosponsor_ids.blank?
        Scoresheet.count! cosponsor_ids, :cosponsored_bills, introduced_at
      end
    end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  include Pagination

  before_filter :require_bill, only: [:show]
  before_filter :load_bills, only: [:index]

  def show
  end

  def index
    Rails.logger.info Bill.distinct(:status)
  end

  private

    def require_bill
      redirect_back unless @bill = Bill.where(id: params[:id]).first
    end

    def load_bills
      @bills = if params[:chamber]
        case params[:chamber]
        when 'house'
          paginate Bill.current.house
        when 'senate'
          paginate Bill.current.senate
        when 'joint'
          paginate Bill.current.joint
        else
          paginate Bill.current
        end
      elsif params[:status]
        case params[:status]
        when 'introduced'
          paginate Bill.current.introduced
        when 'referred'
          paginate Bill.current.referred
        when 'enacted'
          paginate Bill.current.enacted
        when 'defeated'
          paginate Bill.current.defeated
        else
        end
      elsif params[:docket]
        docket = Docket.latest || Docket.new
        docket.bills
      else
        paginate Bill.current
      end
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/index.html.erb
<div class="page-header">
  <h2>Bills and Resolutions</h2>
</div>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'All', bills_page_path(1), :docket, nil %>
    <%= button_bar_link_to 'Upcoming', bills_docket_path(1), :docket %>
  </div>

  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'Introduced', bills_status_path('introduced', 1), :status, 'introduced' %>
    <%= button_bar_link_to 'Referred', bills_status_path('referred', 1), :status, 'referred' %>
    <%= button_bar_link_to 'Enacted', bills_status_path('enacted', 1), :status, 'enacted' %>
    <%= button_bar_link_to 'Defeated', bills_status_path('defeated', 1), :status, 'defeated' %>
  </div>  

  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'Senate', bills_chamber_path('senate', 1), :chamber, 'senate' %>
    <%= button_bar_link_to 'House', bills_chamber_path('house', 1), :chamber, 'house' %>
    <%= button_bar_link_to 'Joint', bills_chamber_path('joint', 1), :chamber, 'joint' %>
  </div>  
</div>

<br />

<table class="table table-condensed table-bordered">
  <tr>
    <th>Name</th><th>Description</th><th>Status</th>
  </tr>
  <% @bills.each do |bill| %>
    <tr>
      <td>
        <strong><%= link_to bill.short_title, bill_path(bill) %></strong>
      </td>
      <td><%= truncate bill.official_title, length: 100 %></td>
      <td><%= bill.status_description %></td>
    </tr>
  <% end %>
</table>

<% unless @bills.empty? %>
  <ul class="pager">
    <% if prior_pages? %>
      <li class="previous">
        <%= link_to "&larr; Newer".html_safe, bills_page_path(prior_page) %>
      </li>
    <% end %>
    <% if more_pages? %>
      <li class="next">
        <%= link_to "Older &rarr;".html_safe, bills_page_path(next_page) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/bills/show.html.erb
<div class="page-header">
  <h2>
  	<%= @bill.display_name %> 
  </h2>
  <h5><%= @bill.official_title %></h5>
</div>

<ul class="nav nav-tabs">
  <li class='active'><a href="#information" data-toggle="tab">Information</a></li>
  <li><a href="#sponsors" data-toggle="tab">Sponsors</a></li>
  <li><a href="#actions" data-toggle="tab">Actions</a></li>
  <li><a href="#amendments" data-toggle="tab">Amendments</a></li>
  <li><a href="#related" data-toggle="tab">Related</a></li>
</ul>
<br />
<div class='tab-content'>
  <div id='information' class='tab-pane active'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Sponsor</h3>
      </div>
      <div class="panel-body">
        <%= link_to @bill.sponsor.name, legislator_path(@bill.sponsor) %>
      </div>
    </div>
  </div>
  <div id='sponsors' class='tab-pane'>
    <% if not @bill.cosponsors.blank? %>
      <table class="table table-condensed table-bordered">
        <tr class='active'>
          <th>Name</th><th>Date</th>
        </tr>
        <% @bill.cosponsors.to_a.sort{|x,y| x.sponsored_at <=> y.sponsored_at }.each do |sponsor| %>
          <tr <%= sponsor.withdrawn? ? "class='danger'" : nil %>>
            <td> 
              <%= link_to sponsor.name, legislator_path(sponsor) %>
            </td>
            <td><%= sponsor.sponsored_at %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <div id='actions' class='tab-pane'>
    <table class="table table-condensed table-bordered">
      <tr><th>Activity</th></tr>
      <% @bill.actions.each do |action| %>
        <tr>
          <td><%= action.created_at %></td>
          <td><%= action.text %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div id='amendments' class='tab-pane'>
    <% unless @bill.amendments.blank? %>
      <table class="table table-condensed table-bordered">
        <tr><th>Purpose</th><th>Sponsor</th><th>Introduced</th></tr>
        <% @bill.amendments.each do |amendment| %>
          <tr>
            <td><small><%= amendment.purpose %></small></td>
            <td><%= link_to amendment.sponsor.name, legislator_path(amendment.sponsor) if amendment.sponsor %></td>
            <td><%= amendment.introduced_at %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <div id='related' class='tab-pane'>
    <% if @bill.related_bills.blank? %>
      <p>There are no bills related to <%= @bill.short_title %>.</p>
    <% else %>
      <table class="table table-condensed table-bordered">
        <tr><th>Name</th></tr>
        <% @bill.related_bills.each do |bill| %>
          <tr>
            <td><%= 'xxx' %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>