config/routes.rb
FantasyCongressLeague::Application.routes.draw do
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :login, only: [] do
    resources :password, only: [:new, :create, :show, :edit, :update], path_names: {edit: 'recover'}
  end
  resources :users, only: [:new, :create, :show]
  resource  :user, only: [:edit, :update], controller: :users
  resources :settings, only: [:edit, :update]
  resources :leagues do
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :team_members, only: [:new, :create] do
        member do
          put :activate, action: :update, defaults: {rpc: 'activate'}
          put :leader, action: :update, defaults: {rpc: 'leader'}
          put :whip, action: :update, defaults: {rpc: 'whip'}
          post :recruit, action: :update, defaults: {rpc: 'recruit'}
          delete :vacate, action: :destroy, defaults: {rpc: 'vacate'}
          delete :recess, action: :destroy, defaults: {rpc: 'recess'}
          delete :retire, action: :destroy, defaults: {rpc: 'retire'}
        end
      end
      resources :tradings, only: [:create, :destroy]
      resources :activity, only: [:index, :show], controller: :annals
      resources :scoresheets, only: [:index]
    end
    member do
      post :authenticate
    end
  end
  get '/leagues/open/page/:id', to: 'leagues#index', as: 'leagues_open', defaults: {state: 'open'}
  get '/leagues/playing/page/:id', to: 'leagues#index', as: 'leagues_playing', defaults: {state: 'playing'}

  resources :legislators, only: [:show, :index] do
    resources :activity, only: [:index, :show], controller: :annals
  end
  get '/legislators/status/:status/page/:id', to: 'legislators#index', as: 'legislators_status'
  get '/legislators/party/:party/page/:id', to: 'legislators#index', as: 'legislators_party'
  get '/legislators/chamber/:chamber/page/:id', to: 'legislators#index', as: 'legislators_chamber'
  get '/legislators/gender/:gender/page/:id', to: 'legislators#index', as: 'legislators_gender'
  get '/legislators/name/:alpha/page/:id', to: 'legislators#index', as: 'legislators_name'
  get '/legislators/page/:id', to: 'legislators#index', as: 'legislators_page'
  get '/legislators/page/:id/:limit', to: 'bills#index', as: 'legislators_page_limit'

  resources :committees, only: [:index, :show]
  get '/committees/page/:id', to: 'committees#index', as: 'committees_page'
  get '/committees/page/:id/:limit', to: 'bills#index', as: 'committees_page_limit'

  resources :bills, only: [:index, :show]
  get '/bills/page/:id', to: 'bills#index', as: 'bills_page'
  get '/bills/page/:id/:limit', to: 'bills#index', as: 'bills_page_limit'
  get '/bills/chamber/:chamber/page/:id', to: 'bills#index', as: 'bills_chamber'
  get '/bills/status/:status/page/:id', to: 'bills#index', as: 'bills_status'
  get '/bills/docket/page/:id', to: 'bills#index', as: 'bills_docket', defaults: {docket: true}

  resource :capital_hill, only: [:show], controller: :capital_hill

  get  'help' => 'home#help'
  get  'statistics' => 'home#statistics'
  root to: 'home#show'
end

app/models/legislator.rb
class Legislator
  include Mongoid::Document
  include Scoring

  field :current, type: Boolean, default: true
  field :cspan_id, type: String
  field :open_secrets_id, type: String
  field :gov_track_id, type: String
  field :votesmart_id, type: String
  field :thomas_id, type: String
  field :twitter_id, type: String
  field :youtube_id, type: String
  field :facebook_id, type: String
  field :last_name, type: String
  field :first_name, type: String
  field :middle_name, type: String
  field :suffix, type: String
  field :title, type: String
  field :description, type: String
  field :gender, type: String
  field :website, type: String
  field :gender, type: String
  field :religion, type: String
  field :birthday, type: Date
  field :attendance, type: Float, default: 100.0

  validates :thomas_id, presence: true

  embeds_many :terms

  has_many :annals

  scope :current, where('current' => true)
  scope :senators, -> { where('terms' => { '$elemMatch' => {'type' => 'sen', 'ends_at' => {'$gte' => Date.today }}} )}
  scope :representatives, -> { where( 'terms' => { '$elemMatch' => {'type' => 'rep', 'ends_at' => {'$gte' => Date.today }}} )}
  scope :veterans, where("this.terms.length > 1")
  scope :rookies, where("this.terms.length == 1")

  index 'terms.type' => 1, 'terms.ends_at' => -1, '_id' => 1
  
  def votes
    Vote.where('voting.legislator_id' => id)
  end

  def sponsored_bills
    Bill.where('sponsor._id' => id).all
  end

  def photo(width=100)
    "http://www.govtrack.us/data/photos/#{gov_track_id}-#{width}px.jpeg" unless gov_track_id.blank?
  end

  def party; term && term.party; end
  def party_abbr; party && term.party[0].upcase; end
  def chamber; term && term.chamber; end
  def chamber_abbr; term && term.chamber[0].upcase; end
  def state; term && term.state; end
  def office; term.senator? ? 'sen.' : 'rep.'; end
  def senator?; office[0] == 's'; end
  def representative?; office[0] == 'r'; end

  def term
    terms.sort{|x,y| y.starts_at <=> x.starts_at }.first
  end

  def committee_memberships
    Committee.where('members._id' => id)
             .map(&:members)
             .flatten
             .select{|m|m._id == id}
  end

  def legislative_activity
    annals.sort{|x,y| y.created_at <=> x.created_at }
  end

  def full_name
    [first_name,middle_name,last_name].select{|n|!n.blank?}.join(' ')
  end

  def display_name
    "#{full_name} [#{party}-#{state}]"
  end

  def short_title
    title && "#{title[0..2]}."
  end

  def in_draft?(drafts)
    drafts.detect{|d| d.legislator_id == id}
  end

  def points
    (scoresheet && scoresheet.points) || 0
  end

  private

    def create_scoresheet
      self.scoresheet ||= Scoresheet.new if new_record?
    end
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController
  include Pagination
  
  before_filter :require_legislator, only: [:show]
  before_filter :load_legislators, only: [:index]

  def show
  	@membership = @legislator.committee_memberships
  	@annals = @legislator.legislative_activity[0..5]
    @bills = @legislator.sponsored_bills
  end

  def index
  end

  private

    def require_legislator
      redirect_back unless @legislator = Legislator.where(id: params[:id]).first
    end

    def load_legislators
      @legislators = Legislator.includes(:scoresheet).current
      @legislators = @legislators.where(gender: /^#{params[:gender]}/i) if params[:gender]
      @legislators = @legislators.where(last_name: /^#{params[:alpha]}/i) if params[:alpha]
      @legislators = @legislators.where('terms.type' => params[:chamber]) if params[:chamber]
      @legislators = @legislators.where('terms.party' => params[:party].titleize) if params[:party]
      if params[:status] == 'veteran'
        @legislators = @legislators.veterans
      elsif params[:status] == 'rookie'
        @legislators = @legislators.rookies
      end
      @legislators = paginate @legislators
    end
end

app/helpers/legislators_helper.rb
module LegislatorsHelper
  def link_to_legislators_page_path(text, page)
    path = if params[:alpha]
      legislators_name_path(params[:alpha], page) 
    elsif params[:chamber]
      legislators_chamber_path params[:chamber], page
    elsif params[:party]
      legislators_party_path params[:party], page
    elsif params[:status]
      legislators_status_path params[:status], page
    else
      legislators_page_path page
    end
    link_to text.html_safe, path
  end
end

app/views/legislators/index.html.erb
<div class="page-header">
  <h2>Legislators</h2>
</div>

<div class="btn-group btn-group-s">
  <%= button_bar_link_to 'All', legislators_path, :alpha, nil %>
  <% alphabet.each do |l| %>
    <%= button_bar_link_to l, legislators_name_path(l, 1), :alpha, l %>
  <% end %>
</div>

<br />
<br />

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'Senate', legislators_chamber_path('sen', 1), :chamber, 'sen' %>
    <%= button_bar_link_to 'House', legislators_chamber_path('rep', 1), :chamber, 'rep' %>
  </div>  

  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'Veterans', legislators_status_path('veteran', 1), :status, 'veteran' %>
    <%= button_bar_link_to 'Rookies', legislators_status_path('rookie', 1), :status, 'rookie' %>
  </div>    

  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'Democrats', legislators_party_path('democrat', 1), :party, 'democrat' %>
    <%= button_bar_link_to 'Republicans', legislators_party_path('republican', 1), :party, 'republican' %>
    <%= button_bar_link_to 'Independents', legislators_party_path('independent', 1), :party, 'independent' %>
  </div>      

  <div class="btn-group btn-group-s">
    <%= button_bar_link_to 'Male', legislators_gender_path('m', 1), :gender, 'm' %>
    <%= button_bar_link_to 'Female', legislators_gender_path('f', 1), :gender, 'f' %>
  </div>    
</div>

<br />

<table class="table table-condensed table-bordered table-striped">
  <tr>
    <th>Legislator</th>
    <th><abbr title='Sponsored bills'>SB</abbr></th>
    <th><abbr title='Cosponsored bills'>CB</abbr></th>
    <th><abbr title='Sponsored enacted bills'>SE</abbr></th>
    <th><abbr title='Coponsored enacted bills'>CE</abbr></th>
    <th><abbr title='Defeated bills'>DB</abbr></th>
    <th><abbr title='Sponsored amendments'>SA</abbr></th>
    <th><abbr title='Passed amendments'>PA</abbr></th>
    <th><abbr title='Clotures won'>CL</abbr></th>
    <th><abbr title='Maverick votes'>MV</abbr></th>
    <th><abbr title='Absences'>AB</abbr></th>
    <th><abbr title='Point total'>PT</abbr></th>
  </tr>
  <% @legislators.each do |legislator| %>
    <tr>
      <td>
        <%= link_to legislator_path(legislator) do %>
          <%= legislator.full_name %> (<%= legislator.chamber_abbr %><%= legislator.party_abbr %>)
        <% end %>
      </td>
      <td><%= legislator.scoresheet.sponsored_bills %></td>
      <td><%= legislator.scoresheet.cosponsored_bills %></td>
      <td><%= legislator.scoresheet.sponsored_enacted_bills %></td>
      <td><%= legislator.scoresheet.cosponsored_enacted_bills %></td>
      <td><%= legislator.scoresheet.defeated_bills %></td>
      <td><%= legislator.scoresheet.sponsored_amendments %></td>
      <td><%= legislator.scoresheet.passed_amendments %></td>
      <td><%= legislator.scoresheet.winning_cloture_votes %></td>
      <td><%= legislator.scoresheet.maverick_votes %></td>
      <td><%= legislator.scoresheet.absences %></td>
      <td><%= legislator.scoresheet.points %></td>
    </tr>
  <% end %>
</table>


<ul class="pager">
<% if prior_pages? %>
  <li class="previous">
    <%= link_to_legislators_page_path "&larr; Previous", prior_page %>
  </li>
<% end %>

<% if more_pages? %>
  <li class="next">
    <%= link_to_legislators_page_path "Next &rarr;", next_page %>
  </li>
<% end %>
</ul>

app/views/legislators/show.html.erb
<div class="page-header">
  <h2>
  	<%= "#{@legislator.short_title} #{@legislator.full_name}" %> 
  	<%= content_tag :small, @legislator.party %>
  </h2>
</div>

<ul class="nav nav-tabs">
  <li class='active'><a href="#overview" data-toggle="tab">Overview</a></li>
  <li><a href="#activity" data-toggle="tab">Activity</a></li>
  <li><a href="#legislation" data-toggle="tab">Legislation</a></li>
  <li><a href="#committees" data-toggle="tab">Committees</a></li>
</ul>

<br />
<div class='tab-content'>
  <div id='overview' class='tab-pane active'>
    <p class='pull-left'><%= image_tag @legislator.photo, :class => 'img-thumbnail img-legislator' %></p>
    <h4><%= @legislator.term.display_name %></h4>

    <%= content_tag :p, "State: #{@legislator.state}" %>
    <%= content_tag :p, "Born: #{@legislator.birthday}" if @legislator.birthday %>
    <%= content_tag :p, "Relgion: #{@legislator.religion}" if @legislator.religion %>

    <p>
      <%= link_to "Website", @legislator.website, target: '_blank' if @legislator.website %>
      <%= link_to "Twitter (@#{@legislator.twitter_id})", "https://twitter.com/#{@legislator.twitter_id}", target: '_blank' if @legislator.twitter_id %>
      <%= link_to "Youtube Channel", "https://youtube.com/user/#{@legislator.youtube_id}", target: '_blank' if @legislator.youtube_id %>
      <%= link_to "Facebook", "https://facebook.com/profile.php?id=#{@legislator.facebook_id}", target: '_blank' if @legislator.facebook_id %>
    </p>

    <%= scoresheet_table @legislator.scoresheet %>
  </div>
  <div id='activity' class='tab-pane'>
    <% unless @annals.blank? %>
      <p>Recent scoring activity | <%= link_to 'View All', legislator_activity_index_path(@legislator) %></p>
    <% end %>
    <table class="table table-condensed table-bordered">
      <% if @annals.blank? %>
        <tr><td>No legislative activity recorded</td></tr>
      <% end %>

      <% @annals.each do |activity| %>
        <tr>
          <td>
            <strong><%= link_to_activity activity %></strong>
          </td>
          <td>
            <%= activity.description.upcase %>
            <em><%= time_ago_in_words activity.created_at %> ago.</em>
          </td>
          <td>+<%= pluralize activity.points, 'point' %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div id='legislation' class='tab-pane'>
    <h4><%= pluralize @bills.size, 'sponsored bill' %></h4>

    <table class="table table-condensed table-bordered">
      <% if @bills.blank? %>
        <tr><td>No bills sponsored</td></tr>
      <% end %>

      <% @bills.each do |bill| %>
        <tr>
          <td>
            <%= link_to bill.display_name, bill_path(bill) %>
          </td>
          <td><%= (bill.last_action.status || bill.last_action.type || '').titleize %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div id='committees' class='tab-pane'>
    <table class="table table-condensed table-bordered">
      <% if @membership.empty? %>
        <tr><td>No committee positions held.</td></tr>
      <% end %>

      <% @membership.each do |member| %>
        <tr>
          <td>
            <strong><%= member.title || 'Member' %></strong>
          </td>
          <td>
            <%= link_to member.committee_name, committee_path(member.committee) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>